name = "Logisticalpack"
author = "theUG"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5f23f076e0fd6f56a146b9a43a6bf9241080e9e0b5ec1ae68ad78727c839b1a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
no-internal-hashes = false
