name = "Logisticalpack"
author = "theUG"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8818436917cfba335015b07f996db13b8c2470700c15b76e12a699a7e69f6c8b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
no-internal-hashes = false
