name = "Logisticalpack"
author = "theUG"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "919b4be4bff5f16b81b7791a2a3ea50b0d0eb88c6b09d0f45ef9f050fb42fa66"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
no-internal-hashes = false
