// /lp_setup_npc — spawn a regional NPC at the player's position.
//
// Usage:
//   /lp_setup_npc <type>           — region auto-detected from current town
//   /lp_setup_npc <type> <region>  — region specified explicitly (override)
//
// Spawns a fresh Easy NPC from the corresponding preset:
//   kubejs/data/easy_npc/preset/humanoid/<type>_<region>.npc.nbt
//
// Auto-region only works inside a registered town (see Phase 3 LPTowns
// registry — town_registry.js). Outside a town, you must specify region
// explicitly. This is intentional: it discourages spawning permanent
// economy NPCs outside their proper context.
//
// The Easy NPC fork (dev-mods/easy-npc-fork/) handles trading registration
// at NBT load time, so no follow-up fix is required after import.

if (typeof LPNpc === 'undefined') var LPNpc = {}

;(function () {
  // Whitelist of supported NPC types. Each must have presets at
  //   kubejs/data/easy_npc/preset/humanoid/<type>_<region>.npc.nbt
  // for every region in LPNpc_REGIONS. Generated by
  //   dev-mods/preset-generator/build_presets.py
  // Add new types in build_presets.py first, regenerate, then list here.
  var LPNpc_TYPES = [
    'innkeeper',
    'town_crier',
    'general_trader',
    'prospector',
    'ore_trader',
    'goods_merchant',
  ]

  // Region keys must match the values produced by
  //   LPTowns.regionForBiome(biomeId)
  // (temperate / cool / arid / tropical) defined in town_registry.js.
  var LPNpc_REGIONS = ['temperate', 'cool', 'arid', 'tropical']

  // ---- helpers ------------------------------------------------------------

  function lpDispEscape(s) {
    return String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"')
  }

  function lpDispTell(src, msg, color) {
    var lpDtTarget
    try {
      lpDtTarget = src.entity ? src.entity.scoreboardName : null
    } catch (e) { lpDtTarget = null }
    if (!lpDtTarget) lpDtTarget = '@a'
    try {
      src.server.runCommandSilent(
        'tellraw ' + lpDtTarget + ' {"text":"' + lpDispEscape(msg)
        + '","color":"' + (color || 'gray') + '"}')
    } catch (eTell) {
      // Fall back to console
      console.log('[LPNpc/dispatcher] tellraw failed (' + eTell + '): ' + msg)
    }
  }

  function lpDispErr(src, msg)  { lpDispTell(src, msg, 'red') }
  function lpDispOk(src, msg)   { lpDispTell(src, msg, 'green') }
  function lpDispWarn(src, msg) { lpDispTell(src, msg, 'yellow') }

  // Look up the player's current chunk in the LPTowns registry. Returns
  // the town's region string (e.g. "temperate") or null if not in a town.
  function lpDispResolveRegion(src) {
    if (typeof LPTowns === 'undefined' || typeof LPTowns.getTown !== 'function') {
      return null
    }
    var lpDrPos = src.position
    if (!lpDrPos) return null
    var lpDrCx = Math.floor(lpDrPos.x) >> 4
    var lpDrCz = Math.floor(lpDrPos.z) >> 4
    var lpDrTown = LPTowns.getTown(src.level, lpDrCx, lpDrCz)
    if (!lpDrTown) return null
    try {
      var lpDrRegion = String(lpDrTown.getString('region'))
      if (lpDrRegion && lpDrRegion.length > 0) return lpDrRegion
    } catch (eR) {}
    return null
  }

  // Validate args + run the import. Returns 1 on success, 0 on failure.
  function lpDispSpawn(src, type, region) {
    if (LPNpc_TYPES.indexOf(type) < 0) {
      lpDispErr(src, '[LPNpc] Unknown NPC type "' + type
        + '". Known: ' + LPNpc_TYPES.join(', '))
      return 0
    }
    if (LPNpc_REGIONS.indexOf(region) < 0) {
      lpDispErr(src, '[LPNpc] Unknown region "' + region
        + '". Known: ' + LPNpc_REGIONS.join(', '))
      return 0
    }
    var lpDsPreset = 'easy_npc:preset/humanoid/' + type + '_' + region + '.npc.nbt'
    var lpDsPos = src.position
    var lpDsCmd = 'easy_npc preset import_new data ' + lpDsPreset
                + ' ' + lpDsPos.x + ' ' + lpDsPos.y + ' ' + lpDsPos.z

    var lpDsResult = -1
    try {
      lpDsResult = src.server.runCommandSilent(lpDsCmd)
    } catch (eRun) {
      lpDispErr(src, '[LPNpc] Spawn command threw: ' + eRun)
      console.warn('[LPNpc/dispatcher] runCommandSilent threw: ' + eRun
        + ' for cmd: ' + lpDsCmd)
      return 0
    }

    if (lpDsResult <= 0) {
      lpDispErr(src, '[LPNpc] Spawn failed (result=' + lpDsResult
        + '). Most likely the preset file does not exist at '
        + lpDsPreset + '. Build it and /reload, then try again.')
      return 0
    }

    lpDispOk(src, '[LPNpc] Spawned ' + type + ' (' + region + ' region) at '
      + Math.round(lpDsPos.x) + ',' + Math.round(lpDsPos.y) + ',' + Math.round(lpDsPos.z))
    return 1
  }

  // ---- command registration ----------------------------------------------

  ServerEvents.commandRegistry(event => {
    // KubeJS exposes the brigadier argument types as uppercase enum
    // constants on event.arguments (ArgumentTypeWrappers). WORD = a single
    // unquoted word; the wrapper has .create(event) -> ArgumentType and
    // .getResult(ctx, name) -> typed value.
    var lpDcWordWrapper = event.arguments.WORD

    // Suggestion providers: tab-complete the known types/regions.
    function lpDcSuggestTypes(ctx, builder) {
      var lpStI
      for (lpStI = 0; lpStI < LPNpc_TYPES.length; lpStI++) {
        builder.suggest(LPNpc_TYPES[lpStI])
      }
      return builder.buildFuture()
    }
    function lpDcSuggestRegions(ctx, builder) {
      var lpSrI
      for (lpSrI = 0; lpSrI < LPNpc_REGIONS.length; lpSrI++) {
        builder.suggest(LPNpc_REGIONS[lpSrI])
      }
      return builder.buildFuture()
    }

    event.register(
      event.commands.literal('lp_setup_npc')
        .requires(src => src.hasPermission(2))
        .then(event.commands.argument('type', lpDcWordWrapper.create(event))
          .suggests(lpDcSuggestTypes)
          // /lp_setup_npc <type>            — auto-detect region from town
          .executes(ctx => {
            var lpEx1Type = String(lpDcWordWrapper.getResult(ctx, 'type'))
            var lpEx1Region = lpDispResolveRegion(ctx.source)
            if (!lpEx1Region) {
              lpDispErr(ctx.source,
                '[LPNpc] Not standing in a registered town. Specify region: '
                + '/lp_setup_npc ' + lpEx1Type + ' <'
                + LPNpc_REGIONS.join('|') + '>')
              return 0
            }
            return lpDispSpawn(ctx.source, lpEx1Type, lpEx1Region)
          })
          .then(event.commands.argument('region', lpDcWordWrapper.create(event))
            .suggests(lpDcSuggestRegions)
            // /lp_setup_npc <type> <region>  — explicit region
            .executes(ctx => {
              var lpEx2Type = String(lpDcWordWrapper.getResult(ctx, 'type'))
              var lpEx2Region = String(lpDcWordWrapper.getResult(ctx, 'region'))
              return lpDispSpawn(ctx.source, lpEx2Type, lpEx2Region)
            })
          )
        )
    )
  })

  console.log('[LPNpc/dispatcher] /lp_setup_npc registered (types='
    + LPNpc_TYPES.join(',') + '; regions=' + LPNpc_REGIONS.join(',') + ')')
})()
