#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu May 07 17:30:23 BST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=Bliss_v2.1.2_(Chocapic13_Shaders_edit).zip
