#This file stores configuration options for Iris, such as the currently active shaderpack
#Sat May 09 23:46:40 BST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=16
shaderPack=Bliss_v2.1.2_(Chocapic13_Shaders_edit).zip
